; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

XLS_file_path3 := A_WorkingDir . "TEST.xls"
Xl := ComObjCreate("Excel.Application")
Xl := ComObjActive("Excel.Application")

Gui Add, Text, x32 y10 w120 h23 +0x200, 거래처 코드
Gui Add, Text, x32 y56 w120 h23 +0x200, 시작 행 번호
Gui Add, Text, x32 y106 w120 h21 +0x200, 입력 품목 건수
Gui Add, Edit, x163 y11 w120 h21 vSANG, Z
Gui Add, Edit, x163 y57 w120 h21 vnum, 2
Gui Add, Edit, x163 y105 w120 h21 vsu, 33
Gui Add, Button, x80 y145 w161 h23 gBtn, 작업 시작

Gui Show, x10 y10 w310 h181, Window
Return

GuiEscape:
GuiClose:
    ExitApp

Btn:
Gui, Submit, NoHide
Send {Ctrl Down}{F2}{Ctrl Up}

;HT01 매출 전표 입력
^F2::
Click,1363,205
Loop 1000
{	
	WorkWindow = WinWaitActive,ahk_class Chrome_WidgetWin_1 
	while (WorkWindow)
	{
			Click,926,202
			Sleep,1000
			Click,453,358
			Sleep,1000
			Send %SANG%
			Sleep,2000
			Send {DOWN}
			Send {ENTER}
			Sleep,2000
			Click,195,442 ;내용선택
			Sleep,1000
        	Send ABC
			Sleep,2000
			Send {ENTER}
			Sleep,1000
			Click,127,506,2
			Send {DEL}
		
		Loop %su%
		{
			VAR=B%num%            ; LEP 
			VAR2=C%num%           ; PART
			var5=E%num%           ; SU
			var7=J%num%
			part := Xl.Range(VAR2).value
			if part =    ; Work Close
				break
			qty := round(Xl.range(var5).value,0)
			lep := Xl.Range(VAR).value
			send %lep%
			Sleep 300	
			send {Tab} %part% {Tab}
			sleep 1000
			send %qty%
			sleep 300
			send {Tab} {Tab} {Tab}
			Xl.Range(var7).value := "OK"
			num++
			if (A_Index > 60)
				break 
		}
		send {enter}
		Quit()
	}

	Quit()
	{
		MsgBox,작업을 종료 합니다.
		Exit
	}

}
Reload

	

^Space::Pause    
	
^PgUp::Reload
	
^PGDN::ExitApp